FALLBACK_SHOT_LIST = [
    {'frame': 1, 'description': "Aldar Köse approaches the greedy merchant's stall with a cunning smile on his face. Aldar Köse, dressed in traditional Kazakh clothing with a feathered hat, waltzes up to a bustling marketplace. His cunning smile is framed by his bushy beard. The camera angle is from a low position, making Aldar appear larger than life."},
    {'frame': 2, 'description': 'Aldar Köse and the merchant engage in a lively conversation, Aldar pointing to a horse. Aldar gestures excitedly to a sturdy horse tied up nearby. The merchant, a portly man draped in luxurious robes, looks intrigued yet cautious. The camera captures their exchange from a middle-long shot angle.'},
    {'frame': 3, 'description': "Aldar Köse hatches his plan and begins to spin his elaborate scheme to the merchant. The scene is shot from the merchant's perspective. Aldar leans in, speaking in hushed tones. His eyes sparkle with a hint of mischief."},
    {'frame': 4, 'description': "The merchant seems skeptical, but Aldar continues his persuasive tactics. The camera switches to a high angle shot focusing on Aldar, capturing the merchant's hesitant expressions and Aldar's determined, cunning face."},
    {'frame': 5, 'description': "Winning over the merchant, Aldar Köse shakes hands with him to finalize the deal. A close shot of their handshake, Aldar's grin is even wider, but the merchant still appears unsure. The transaction is happening under the bright midday sun, casting vibrant colors over the bustling marketplace."},
    {'frame': 6, 'description': "Aldar takes the reins of the horse and mounts it, waving the merchant farewell. The camera transitions to a long shot as Aldar hops onto the horse. Aldar's vibrant traditional clothes stand out against the dusty marketplace ground."},
    {'frame': 7, 'description': 'Aldar rides away from the merchant, still laughing and waving. Captured from a low angle, Aldar looks triumphant as he rides away on his newly acquired horse. His laughter can be visually perceived through his wide-open mouth and uplifted head.'},
    {'frame': 8, 'description': "The merchant, left in Aldar's dust, realizes his mistake. Shot from Aldar's perspective, the merchant stands alone in the marketplace, a shocked expression on his face as he grasps the emptiness of his mistake. The surrounding crowd seem oblivious, carrying on with their trading."}
]